version: "3.8"

services:
  web:
    build: .
    expose:
      - "8000"  # Updated for Gunicorn on port 8000
    environment:
      DB_HOST: mysqldb
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: mydb
    depends_on:
      - mysqldb

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
