name: Python Lint, Format, and Type Check

on: [push, pull_request]


jobs:
  lint-format-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker
        run: docker compose up --build -d

      - name: Install dependencies
        run: pip install mypy black isort pylint

      - name: Check import sorting with isort
        uses: isort/isort-action@v1
        with:
          configuration: "--profile black --check-only --diff"

      - name: Check code formatting with Black
        run: black --check .

