name: Python Lint, Format, and Type Check

on: [push, pull_request]

jobs:
  lint-format-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy black isort pylint

      - name: Check import sorting with isort
        run: |
          isort . --profile black --check --diff

      - name: Check code formatting with Black
        run: |
          black --check .

      - name: Lint with pylint
        run: |
          find . -type f -name "*.py" ! -path "./venv/*" -print0 | xargs -0 pylint

      - name: Type check with mypy
        run: |
          mypy .
