name: Pip Audit on requirements.txt 

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pip-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.0' 
          
      - name: Install pip-audit
        run: pip install --upgrade pip-audit

      - name: Run pip-audit on requirements.txt 
        run: |
          pip-audit -r requirements.txt || echo "Vulnerabilities found:"

