name: Pip Audit on requirements.txt 

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pip-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.0'

      - name: Install from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Freeze installed packages to temp file
        run: |
          pip freeze > audited-requirements.txt
          echo "Auditing the following packages"
          cat audited-requirements.txt

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Run pip-audit on frozen requirements
        run: pip-audit -r audited-requirements.txt || echo "⚠️ Vulnerabilities found:)"

