name: Validate

on:
  push:
    branches:
      - main
  pull_request:

# checks whether your Nginx container is correctly configured to reverse proxy requests  
# to the Flask application running in a separate Docker container

jobs:

# lint the python files
  lint-pythonfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f flask/requirements.txt ]; then pip install -r flask/requirements.txt; fi

      - name: Lint with pylint
        run: |
          pylint app.py data_source/*.py domain/*/*.py presentation/controller/*.py