name: Validate

on:
  push:
    branches:
      - main
  pull_request:

# checks whether your Nginx container is correctly configured to reverse proxy requests  
# to the Flask application running in a separate Docker container

jobs:

# lint the python files
  lint-pythonfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker
        run: docker compose up --build -d

      - name: Install dependencies
        run: |
          pip install pylint

      - name: Lint with pylint
        run: |
          pylint app.py data_source/*.py domain/*/*.py presentation/controller/*.py